---
title: "Old Chrome_Revenue"
author: "Duvan"
date: "1/13/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
##Connection to DBs


### ALERT: Red Flag: Update week date on the 6 Connections and Update date on graphs labels
```{r, All Flags}

## Red Flag Clicks
### Agencies with chrome clicks < 90

Red_OCR <- dbGetQuery (conCH, "SELECT SUM(`clickOut`), `agencyId` FROM ext_Lastmonth.browserName_browserVersion WHERE `date` >= '2022-2-23' AND `date` <= '2022-2-28' AND `browser` = 'Chrome' AND `browserVers` < '90' GROUP BY `agencyId` LIMIT 1000") 


is.na(Red_OCR) <- Red_OCR == ""
is.na(Red_OCR) <- Red_OCR == "-1"
is.na(Red_OCR) <- Red_OCR == "0"
is.na(Red_OCR) <- Red_OCR == "nf"
is.na(Red_OCR) <- Red_OCR == "tm"

## Cleaning and Format

Red_OCR$`sum(clickOut)` <- as.numeric(Red_OCR$`sum(clickOut)`)
Red_OCR$agencyId <- as.integer(Red_OCR$agencyId)
Red_OCR <- na.omit(Red_OCR) 
setnames(Red_OCR, "sum(clickOut)", "old_chromeCk")

## Orange Flag Clicks 
### Agencies with chrome clicks between (90-95)

Orange_OCR <- dbGetQuery (conCH, "SELECT SUM(`clickOut`), `agencyId` FROM ext_Lastmonth.browserName_browserVersion WHERE `date` >= '2022-2-23' AND `date` <= '2022-2-28' AND `browser` = 'Chrome' AND `browserVers` >= '90' AND `browserVers` < '95' GROUP BY `agencyId` LIMIT 1000")



is.na(Orange_OCR) <- Orange_OCR == ""
is.na(Orange_OCR) <- Orange_OCR == "-1"
is.na(Orange_OCR) <- Orange_OCR == "0"
is.na(Orange_OCR) <- Orange_OCR == "nf"
is.na(Orange_OCR) <- Orange_OCR == "tm"


Orange_OCR$`sum(clickOut)` <- as.numeric(Orange_OCR$`sum(clickOut)`)
Orange_OCR$agencyId <- as.integer(Orange_OCR$agencyId)
Orange_OCR <- na.omit(Orange_OCR) ## Cleaning Data
setnames(Orange_OCR, "sum(clickOut)", "old_chromeCk")


## Yellow Flag Clicks 
### Agencies with chrome clicks between (95-96)


Yellow_OCR <- dbGetQuery (conCH, "SELECT SUM(`clickOut`), `agencyId` FROM ext_Lastmonth.browserName_browserVersion WHERE `date` >= '2022-2-23' AND `date` <= '2022-2-28' AND `browser` = 'Chrome' AND `browserVers` >= '95' AND `browserVers` <= '96' GROUP BY `agencyId` LIMIT 1000")



is.na(Yellow_OCR) <- Yellow_OCR == ""
is.na(Yellow_OCR) <- Yellow_OCR == "-1"
is.na(Yellow_OCR) <- Yellow_OCR == "0"
is.na(Yellow_OCR) <- Yellow_OCR == "nf"
is.na(Yellow_OCR) <- Yellow_OCR == "tm"


Yellow_OCR$`sum(clickOut)` <- as.numeric(Yellow_OCR$`sum(clickOut)`)
Yellow_OCR$agencyId <- as.integer(Yellow_OCR$agencyId)
Yellow_OCR <- na.omit(Yellow_OCR) ## Cleaning Data
setnames(Yellow_OCR, "sum(clickOut)", "old_chromeCk")



########### Joining the 3 flags here before generic metrics


red_orange <- full_join(Red_OCR, Orange_OCR, by = "agencyId")

roy_rate <- full_join(red_orange, Yellow_OCR, by = "agencyId")

roy_rate[is.na(roy_rate)] <- 0

setnames(roy_rate, "old_chromeCk.x", "red_clicks")
setnames(roy_rate, "old_chromeCk.y", "orange_clicks")
setnames(roy_rate, "old_chromeCk", "yellow_clicks")



## Query 1: gross total

gross_agencies <- sqlQuery(ConMy, "SELECT SQL_CALC_FOUND_ROWS SUM(`gross`), `agencyId` FROM externalAgenciesReport.comparisonView WHERE `date` >= '2022-2-23' AND `date` <= '2022-2-28' GROUP BY `agencyId` LIMIT 1000")


### Joining 1- Adding gross_total

gross_royrate <- inner_join(roy_rate, gross_agencies, by = "agencyId")
setnames(gross_royrate, "SUM(`gross`)", "gross_total")


## Query 2: Chrome Clicks

allChrome_clicksout <- dbGetQuery (conCH, "SELECT SUM(`clickOut`), `agencyId` FROM ext_Lastmonth.browserName_browserVersion WHERE `date` >= '2022-2-23' AND `date` <= '2022-2-28' AND `browser` = 'Chrome' GROUP BY `agencyId` LIMIT 1000")

allChrome_clicksout$agencyId <- as.integer(allChrome_clicksout$agencyId)

### Joining 2: Adding Chrome_clicks

royrate_chromeCk <- inner_join(gross_royrate, allChrome_clicksout, by = "agencyId")
setnames(royrate_chromeCk, "sum(clickOut)", "Chrome_clicks")

#### 3 Query: Clicks_total ### Fix the general in all clicks

allClicks <- dbGetQuery (conCH, "SELECT SUM(`clickOut`), `agencyId` FROM ext_Lastmonth.browserName_browserVersion WHERE `date` >= '2022-2-23' AND `date` <= '2022-2-28' GROUP BY `agencyId` LIMIT 10000000")

allClicks$agencyId <- as.integer(allClicks$agencyId)

### Joining 3: Adding Clicks_total 

roy_allClicks <- inner_join(royrate_chromeCk, allClicks, by = "agencyId")
setnames(roy_allClicks, "sum(clickOut)", "Clicks_total")


#### Query 4: Agencies names 

agencies_nam <- sqlQuery(ConMy,"SELECT id, name FROM externalAgencies.agencies LIMIT 1000")
setnames(agencies_nam, "id", "agencyId")
agencies_nam$agencyId <- as.integer(agencies_nam$agencyId)

# Joining 4: Agencies names 

Flags <- inner_join(roy_allClicks, agencies_nam, by = "agencyId")
Flags <- within(Flags, agency <- paste(Flags$name, Flags$agencyId, sep=' ')) 


### Adding New Columns with calculations

### Red calculations

Flags$cpc <- as.numeric(Flags$gross_total / Flags$Clicks_total)
Flags$cpc <- round(Flags$cpc, digits=2)

Flags$red_chromerate <- as.numeric(Flags$red_clicks / Flags$Chrome_clicks)
Flags$red_chromerate <- round(Flags$red_chromerate, digits=2)

Flags$red_rate <- as.numeric(Flags$red_clicks / Flags$Clicks_total) 
Flags$red_rate <- round(Flags$red_rate, digits=2)

Flags$redGross <- as.numeric(Flags$red_clicks * Flags$cpc)

### Orange calculations


Flags$orange_chromerate <- as.numeric(Flags$orange_clicks / Flags$Chrome_clicks)
Flags$orange_chromerate <- round(Flags$orange_chromerate, digits=2)

Flags$orange_rate <- as.numeric(Flags$orange_clicks / Flags$Clicks_total) 
Flags$orange_rate <- round(Flags$orange_rate, digits=2)

Flags$orangeGross <- as.numeric(Flags$orange_clicks * Flags$cpc)

#### Yellow Calculations

Flags$yellow_chromerate <- as.numeric(Flags$yellow_clicks / Flags$Chrome_clicks)
Flags$yellow_chromerate <- round(Flags$yellow_chromerate, digits=2)

Flags$yellow_rate <- as.numeric(Flags$yellow_clicks / Flags$Clicks_total) 
Flags$yellow_rate <- round(Flags$yellow_rate, digits=2)

Flags$yellowGross <- as.numeric(Flags$yellow_clicks * Flags$cpc)

###
Flags$agencyId <- as.character(Flags$agencyId)




```

```{r Graph - Red Flag}


## in % 

library(ggplot2)

ggplot(data=Flags, aes(x=agency, y=red_rate, group=1)) +
  geom_line(color="red", size = 2)+
  geom_point(color = "black", size = 5) + 
    geom_hline(yintercept = mean(Flags$red_rate), size = 1) +
  scale_y_continuous(n.breaks = 10, labels = percent_format()) +
  theme(axis.text.x = element_text(face = "bold", angle = 65, hjust = 1)) +
 labs( title = "Red Rate", 
         subtitle = "Feb 23 - 28", 
         x = "",
         y = "Red rate")

mean(Red_OCR$oldBrowser_rate)

## In Money

ggplot(data=Flags, aes(x=agency, y=redGross, group=1))+
  geom_line(color="red", size = 2) +
  geom_point(color = "black", size = 5) + 
  geom_hline(yintercept = mean(Flags$redGross), size = 1) +
  scale_y_continuous(n.breaks = 10, labels = dollar_format()) +
 theme(axis.text.x = element_text(face = "bold", angle = 65, hjust = 1)) +
   labs( title = "Estimate revenue from old browsers", 
         subtitle = "Feb 23 - 28", 
         x = "",
         y = " Estimate gross Revenue")


```

```{r Graph - Orange Flag}


## in % 

library(ggplot2)

ggplot(data=Orange_flag, aes(x=agency, y=orange_rate, group=1)) +
  geom_line(color="orange", size = 2)+
  geom_point(color = "black", size = 3) + 
    geom_hline(yintercept = mean(Orange_flag$orange_rate), size = 1) +
   scale_y_continuous(n.breaks = 10, labels = percent_format()) +
  theme(axis.text.x = element_text(face = "bold", angle = 65, hjust = 1)) +
 labs( title = "Orange Rate", 
         subtitle = "Feb 23 - 23", 
         x = "",
         y = "Orange Rate")

## In Money

ggplot(data=Orange_flag, aes(x=agency, y=orangeGross, group=1))+
  geom_line(color="orange", size = 2) +
  geom_point(color = "black", size = 3) + 
  geom_hline(yintercept = mean(Orange_flag$orangeGross), size = 1) +
  scale_y_continuous(n.breaks = 10, labels = dollar_format()) +
 theme(axis.text.x = element_text(face = "bold", angle = 65, hjust = 1)) +
  labs( title = "Estimate revenue from old browsers", 
         subtitle = "Feb 23 - 28", 
         x = "",
         y = "Estimate gross revenue")
```

```{r Graph - Yellow Flag}


## in % 

library(ggplot2)

ggplot(data=Yellow_flag, aes(x=agency, y=yellow_rate, group=1)) +
  geom_line(color="Yellow", size = 2)+
  geom_point(color = "black", size = 3) +
   geom_hline(yintercept = mean(Yellow_flag$yellow_rate), size = 1) +
 scale_y_continuous(n.breaks = 10, labels = percent_format()) +
  theme(axis.text.x = element_text(face = "bold", angle = 65, hjust = 1)) +
labs( title = "Yellow Rate", 
         subtitle = "Feb 23 - 28", 
         x = "",
         y = "Yellow rate")

## In Money

ggplot(data=Yellow_flag, aes(x=agency, y=yellowGross, group=1))+
  geom_line(color="yellow", size = 2) +
  geom_point(color = "black", size = 3) +
  geom_hline(yintercept = mean(Yellow_flag$yellowGross), size = 1) +
  scale_y_continuous(n.breaks = 10, labels = dollar_format()) +
 theme(axis.text.x = element_text(face = "bold", angle = 65, hjust = 1)) +
  labs( title = "Estimate revenue from old browsers", 
         subtitle = "Feb 23 - 28", 
         x = "",
         y = "Estimate gross Revenue")

```

### Update date in the 5 queries
```{r, Adding others metrics}

## Query declinedRate

declinedRate <- sqlQuery(ConMy, "SELECT SQL_CALC_FOUND_ROWS `agencyId`, AVG(`declinedRateCOut`), `agencyId` FROM externalAgenciesReport.declinedRate WHERE `date` >= '2022-2-23' AND `date` <= '2022-2-28' GROUP BY `agencyId`, `agencyId` LIMIT 1000000")

declinedRate$agencyId <- as.character(declinedRate$agencyId)
setnames(declinedRate, "AVG(`declinedRateCOut`)", "declinadedRate_avg")


df_declinedRate <- left_join(Flags, declinedRate, by = "agencyId")



### Query Clicks yesterday

Clicks_yest <- dbGetQuery (conCH, "SELECT SUM(`clickOut`), `agencyId` FROM ext_Lastmonth.browserName_browserVersion WHERE `date` = '2022-2-27' GROUP BY `agencyId` LIMIT 1000000")

setnames(Clicks_yest, "sum(clickOut)", "clicks_yest")


df_clicksYes <- left_join(df_declinedRate, Clicks_yest, by = "agencyId")



###Query detecting FingerPrint 
### campname above > 0.1 / 1%

fPrint <- dbGetQuery (conCH, "SELECT AVG(`session%`), `agencyId` FROM ext_Lastmonth.FingerPrintMismatch WHERE `date` >= '2022-2-23' AND `date` <= '2022-2-28' GROUP BY `agencyId` LIMIT 10000000")

is.na(fPrint) <- fPrint == ""
is.na(fPrint) <- fPrint == "nf;"
is.na(fPrint) <- fPrint == "nf,"
is.na(fPrint) <- fPrint == "nf&"
is.na(fPrint) <- fPrint == "http://182241055:57022/AppScanMsg.html?varId=664"
is.na(fPrint) <- fPrint == "HCL4ppsc4nbuggyRandomValue"
is.na(fPrint) <- fPrint == "AnfB"
is.na(fPrint) <- fPrint == "AB"
is.na(fPrint) <- fPrint == "ping -c 1 v3-ping-650-440f7dbf-9266-4fa6-a277-b847d5ea696f.securityip.appsechcl.com"
is.na(fPrint) <- fPrint == "WFXSSProbe"
is.na(fPrint) <- fPrint == "-1"
is.na(fPrint) <- fPrint == "0"
is.na(fPrint) <- fPrint == "nf("
is.na(fPrint) <- fPrint == "ss"
is.na(fPrint) <- fPrint == "ProbePhishing"
is.na(fPrint) <- fPrint == "nfxttoprobeut00000Cxt"
is.na(fPrint) <- fPrint == "nf>"
is.na(fPrint) <- fPrint == "tm"
is.na(fPrint) <- fPrint == "nf<"
is.na(fPrint) <- fPrint == "hfwbprobeey000949hf"

fPrint <- na.omit(fPrint) ## Cleaning Data

fPrint$`avg(session%)` <- as.numeric(fPrint$`avg(session%)`)
setnames(fPrint, "avg(session%)", "fingerPrint_Rate")


str(fPrint$agencyId) ## Character


df_fPrint <- left_join(df_clicksYes, fPrint, by = "agencyId")



###Query detecting headless Chrome
### campname above > 0.3 (3%)


###Query with headLessChrome Rate by campaings

headlessC_rate <- dbGetQuery (conCH, "SELECT AVG(`HeadlessChrome_%`), `agencyId` FROM ext_Lastmonth.botByCampname WHERE `date` >= '2022-2-23' AND `date` <= '2022-2-28' GROUP BY `agencyId` LIMIT 10000000")


is.na(headlessC_rate) <- headlessC_rate == "AtmB"
is.na(headlessC_rate) <- headlessC_rate == "WF SQL Probe;A--B"
is.na(headlessC_rate) <- headlessC_rate == "wget http://10.220.198.66:59428/AppScanMsg.html?varId=728"
is.na(headlessC_rate) <- headlessC_rate == "tm%3E(wget%20http%3A%2F%2F10.220.192.18%3A60717%2FAppScanMsg.html%3FvarId%3D992)"
is.na(headlessC_rate) <- headlessC_rate == "tm%7C%7Cwget%20http%3A%2F%2F10.220.192.18%3A58597%2FAppScanMsg.html%3FvarId%3D765"
is.na(headlessC_rate) <- headlessC_rate == "tm%3E(wget%20http%3A%2F%2F10.220.192.18%3A60717%2FAppScanMsg.html%3FvarId%3D992)"
is.na(headlessC_rate) <- headlessC_rate == "nf"
is.na(headlessC_rate) <- headlessC_rate == "ss"
is.na(headlessC_rate) <- headlessC_rate == "ProbePhishing"
is.na(headlessC_rate) <- headlessC_rate == "nfxttoprobeut00000Cxt"
is.na(headlessC_rate) <- headlessC_rate == "hfwbprobeey000949hf"
is.na(headlessC_rate) <- headlessC_rate == "tm"
is.na(headlessC_rate) <- headlessC_rate == "wget%20http%3A%2F%2F10.220.198.66%3A59428%2FAppScanMsg.html%3FvarId%3D740"
is.na(headlessC_rate) <- headlessC_rate == "wget http://10.220.192.18:59265/AppScanMsg.html?varId=2764"
is.na(headlessC_rate) <- headlessC_rate == ";"
is.na(headlessC_rate) <- headlessC_rate == "wget http://10.220.192.18:58597/AppScanMsg.html?varId=747"
is.na(headlessC_rate) <- headlessC_rate == "v3-ping-836-85aca81b-1376-444d-8ef8-eaa7a071c1a1.securityip.appsechcl.com"
is.na(headlessC_rate) <- headlessC_rate == "v3-ping-3083-8efef79e-d8a1-4c06-8463-8420294a940d.securityip.appsechcl.com"
is.na(headlessC_rate) <- headlessC_rate == "tmwsozprobeyn000428ws"
is.na(headlessC_rate) <- headlessC_rate == "tm>"
is.na(headlessC_rate) <- headlessC_rate == "tm<"
is.na(headlessC_rate) <- headlessC_rate == "tm\r\n\r\n"
is.na(headlessC_rate) <- headlessC_rate == "tm;"
is.na(headlessC_rate) <- headlessC_rate == "wget%20http%3A%2F%2F10.220.192.18%3A59265%2FAppScanMsg.html%3FvarId%3D2776"
is.na(headlessC_rate) <- headlessC_rate == "tmWFXSSProbe"
is.na(headlessC_rate) <- headlessC_rate == "tmclolprobepc000014cl"
is.na(headlessC_rate) <- headlessC_rate == "wsozprobeyn000428ws"
is.na(headlessC_rate) <- headlessC_rate == "AnfB"
is.na(headlessC_rate) <- headlessC_rate == "tm%3Bwget%20http%3A%2F%2F10.220.192.18%3A59265%2FAppScanMsg.html%3FvarId%3D497"
is.na(headlessC_rate) <- headlessC_rate == "tm || wget http://10.220.198.66:56481/AppScanMsg.html?varId=786"
is.na(headlessC_rate) <- headlessC_rate == "tm ping -c 1 v3-ping-769-7fcbfd33-0127-4b0b-be40-6c037eea8134.securityip.appsechcl.com"
is.na(headlessC_rate) <- headlessC_rate == "tm >(ping -c 1 v3-ping-771-7fcbfd33-0127-4b0b-be40-6c037eea8134.securityip.appsechcl.com)"
is.na(headlessC_rate) <- headlessC_rate == "http://182240834:59428/AppScanMsg.html?varId=777"
is.na(headlessC_rate) <- headlessC_rate == "http://"
is.na(headlessC_rate) <- headlessC_rate == "ping -c 1 v3-ping-3062-8efef79e-d8a1-4c06-8463-8420294a940d.securityip.appsechcl.com"
is.na(headlessC_rate) <- headlessC_rate == "ping -c 1 v3-ping"
is.na(headlessC_rate) <- headlessC_rate == "tmnvieprobeci00038Anv"
is.na(headlessC_rate) <- headlessC_rate == "ping -c 1 v3-ping-650-440f7dbf-9266-4fa6-a277-b847d5ea696f.securityip.appsechcl.com"
is.na(headlessC_rate) <- headlessC_rate == "WFXSSProbe"
is.na(headlessC_rate) <- headlessC_rate == "AB"
is.na(headlessC_rate) <- headlessC_rate == "AtmB"
is.na(headlessC_rate) <- headlessC_rate == "etmtprobeec0001C7et"
is.na(headlessC_rate) <- headlessC_rate == "HCL4ppsc4nbuggyRandomValue"




headlessC_rate <- na.omit(headlessC_rate) ## Cleaning Data
headlessC_rate$`avg(HeadlessChrome_%)` <- as.numeric(headlessC_rate$`avg(HeadlessChrome_%)`)
setnames(headlessC_rate, "avg(HeadlessChrome_%)", "headlessChrome_rate")


str(headlessC_rate$agencyId) ## Character


df_headless <- inner_join(df_fPrint, headlessC_rate,  by = "agencyId")


#### Adding Tq rate 


tq <- sqlQuery(ConMy, "SELECT SQL_CALC_FOUND_ROWS AVG(`tq`), `agencyId`, `clicksIn`, `clicksOut`, `ctr` FROM externalAgenciesReport.comparisonView WHERE `date` >= '2022-2-23' AND `date` <= '2022-2-28' GROUP BY `agencyId` LIMIT 2000000000")


setnames(tq, "AVG(`tq`)", "Tq_avg")

tq$agencyId <- as.character(tq$agencyId)




df_messy <- left_join(df_headless, tq,  by = "agencyId")


df = df_messy %>% select(agency, Clicks_total, Chrome_clicks, red_clicks, gross_total, red_rate, redGross, orange_rate, orangeGross, yellow_rate, yellowGross, declinadedRate_avg, clicks_yest, fingerPrint_Rate, headlessChrome_rate, Tq_avg)
                    
names (df)



##Exporting the full Table

write.table(df, file= "chrome_fb28.csv", sep = ",", row.names = F)


```

```{r Correlation}


plot(df$red_rate ~ df$headlessChrome_rate)
plot(df$Tq_avg ~ df$headlessChrome_rate)

cor(df$Tq_avg, df$headlessChrome_rate)


```

```{r, Google Data Studio}

## Red Flag Clicks
### Agencies with chrome clicks < 90

Red_OCR <- dbGetQuery (conCH, "SELECT SUM(`clickOut`), `agencyId` FROM ext_Lastmonth.browserName_browserVersion WHERE `date` >= '2022-2-23' AND `date` <= '2022-2-28' AND `browser` = 'Chrome' AND `browserVers` < '90' GROUP BY `agencyId` LIMIT 1000") 


is.na(Red_OCR) <- Red_OCR == ""
is.na(Red_OCR) <- Red_OCR == "-1"
is.na(Red_OCR) <- Red_OCR == "0"
is.na(Red_OCR) <- Red_OCR == "nf"
is.na(Red_OCR) <- Red_OCR == "tm"

## Cleaning and Format

Red_OCR$`sum(clickOut)` <- as.numeric(Red_OCR$`sum(clickOut)`)
Red_OCR$agencyId <- as.integer(Red_OCR$agencyId)
Red_OCR <- na.omit(Red_OCR) 
setnames(Red_OCR, "sum(clickOut)", "old_chromeCk")

## Orange Flag Clicks 
### Agencies with chrome clicks between (90-95)

Orange_OCR <- dbGetQuery (conCH, "SELECT SUM(`clickOut`), `agencyId` FROM ext_Lastmonth.browserName_browserVersion WHERE `date` >= '2022-2-23' AND `date` <= '2022-2-28' AND `browser` = 'Chrome' AND `browserVers` >= '90' AND `browserVers` < '95' GROUP BY `agencyId` LIMIT 1000")



is.na(Orange_OCR) <- Orange_OCR == ""
is.na(Orange_OCR) <- Orange_OCR == "-1"
is.na(Orange_OCR) <- Orange_OCR == "0"
is.na(Orange_OCR) <- Orange_OCR == "nf"
is.na(Orange_OCR) <- Orange_OCR == "tm"


Orange_OCR$`sum(clickOut)` <- as.numeric(Orange_OCR$`sum(clickOut)`)
Orange_OCR$agencyId <- as.integer(Orange_OCR$agencyId)
Orange_OCR <- na.omit(Orange_OCR) ## Cleaning Data
setnames(Orange_OCR, "sum(clickOut)", "old_chromeCk")


## Yellow Flag Clicks 
### Agencies with chrome clicks between (95-96)


Yellow_OCR <- dbGetQuery (conCH, "SELECT SUM(`clickOut`), `agencyId` FROM ext_Lastmonth.browserName_browserVersion WHERE `date` >= '2022-2-23' AND `date` <= '2022-2-28' AND `browser` = 'Chrome' AND `browserVers` >= '95' AND `browserVers` <= '96' GROUP BY `agencyId` LIMIT 1000")



is.na(Yellow_OCR) <- Yellow_OCR == ""
is.na(Yellow_OCR) <- Yellow_OCR == "-1"
is.na(Yellow_OCR) <- Yellow_OCR == "0"
is.na(Yellow_OCR) <- Yellow_OCR == "nf"
is.na(Yellow_OCR) <- Yellow_OCR == "tm"


Yellow_OCR$`sum(clickOut)` <- as.numeric(Yellow_OCR$`sum(clickOut)`)
Yellow_OCR$agencyId <- as.integer(Yellow_OCR$agencyId)
Yellow_OCR <- na.omit(Yellow_OCR) ## Cleaning Data
setnames(Yellow_OCR, "sum(clickOut)", "old_chromeCk")



########### Joining the 3 flags here before generic metrics


red_orange <- full_join(Red_OCR, Orange_OCR, by = "agencyId")

roy_rate <- full_join(red_orange, Yellow_OCR, by = "agencyId")

roy_rate[is.na(roy_rate)] <- 0

setnames(roy_rate, "old_chromeCk.x", "red_clicks")
setnames(roy_rate, "old_chromeCk.y", "orange_clicks")
setnames(roy_rate, "old_chromeCk", "yellow_clicks")



## Query 1: gross total

gross_agencies <- sqlQuery(ConMy, "SELECT SQL_CALC_FOUND_ROWS SUM(`gross`), `agencyId` FROM externalAgenciesReport.comparisonView WHERE `date` >= '2022-2-23' AND `date` <= '2022-2-28' GROUP BY `agencyId` LIMIT 1000")



### Joining 1- Adding gross_total

gross_royrate <- inner_join(roy_rate, gross_agencies, by = "agencyId")
setnames(gross_royrate, "SUM(`gross`)", "gross_total")


## Query 2: Chrome Clicks

allChrome_clicksout <- dbGetQuery (conCH, "SELECT SUM(`clickOut`), `agencyId` FROM ext_Lastmonth.browserName_browserVersion WHERE `date` >= '2022-2-23' AND `date` <= '2022-2-28' AND `browser` = 'Chrome' GROUP BY `agencyId` LIMIT 1000")

allChrome_clicksout$agencyId <- as.integer(allChrome_clicksout$agencyId)

### Joining 2: Adding Chrome_clicks

royrate_chromeCk <- inner_join(gross_royrate, allChrome_clicksout, by = "agencyId")
setnames(royrate_chromeCk, "sum(clickOut)", "Chrome_clicks")

#### 3 Query: Clicks_total ### Fix the general in all clicks

allClicks <- dbGetQuery (conCH, "SELECT SUM(`clickOut`), `agencyId` FROM ext_Lastmonth.browserName_browserVersion WHERE `date` >= '2022-2-23' AND `date` <= '2022-2-28' GROUP BY `agencyId` LIMIT 10000000")

allClicks$agencyId <- as.integer(allClicks$agencyId)

### Joining 3: Adding Clicks_total 

roy_allClicks <- inner_join(royrate_chromeCk, allClicks, by = "agencyId")
setnames(roy_allClicks, "sum(clickOut)", "Clicks_total")


#### Query 4: Agencies names 

agencies_nam <- sqlQuery(ConMy,"SELECT id, name FROM externalAgencies.agencies LIMIT 1000")
setnames(agencies_nam, "id", "agencyId")
agencies_nam$agencyId <- as.integer(agencies_nam$agencyId)

# Joining 4: Agencies names 

Flags <- inner_join(roy_allClicks, agencies_nam, by = "agencyId")
Flags <- within(Flags, agency <- paste(Flags$name, Flags$agencyId, sep=' ')) 


### Adding New Columns with calculations

### Red calculations

Flags$cpc <- as.numeric(Flags$gross_total / Flags$Clicks_total)
Flags$cpc <- round(Flags$cpc, digits=2)

Flags$red_chromerate <- as.numeric(Flags$red_clicks / Flags$Chrome_clicks)
Flags$red_chromerate <- round(Flags$red_chromerate, digits=2)

Flags$red_rate <- as.numeric(Flags$red_clicks / Flags$Clicks_total) 
Flags$red_rate <- round(Flags$red_rate, digits=2)

Flags$redGross <- as.numeric(Flags$red_clicks * Flags$cpc)

### Orange calculations


Flags$orange_chromerate <- as.numeric(Flags$orange_clicks / Flags$Chrome_clicks)
Flags$orange_chromerate <- round(Flags$orange_chromerate, digits=2)

Flags$orange_rate <- as.numeric(Flags$orange_clicks / Flags$Clicks_total) 
Flags$orange_rate <- round(Flags$orange_rate, digits=2)

Flags$orangeGross <- as.numeric(Flags$orange_clicks * Flags$cpc)

#### Yellow Calculations

Flags$yellow_chromerate <- as.numeric(Flags$yellow_clicks / Flags$Chrome_clicks)
Flags$yellow_chromerate <- round(Flags$yellow_chromerate, digits=2)

Flags$yellow_rate <- as.numeric(Flags$yellow_clicks / Flags$Clicks_total) 
Flags$yellow_rate <- round(Flags$yellow_rate, digits=2)

Flags$yellowGross <- as.numeric(Flags$yellow_clicks * Flags$cpc)

###
Flags$agencyId <- as.character(Flags$agencyId)




```



### TOP 100 Campaigns - Update teh date in the 6 queries

```{r Red Flag - Top 100 campaigns}

## Query Campaigns with Old Chrome, order by Clicks Out

Red_100camp <- dbGetQuery (conCH, "SELECT SUM(`clickOut`), `agencyId`, `campname` FROM ext_Lastmonth.browserName_browserVersion WHERE `date` >= '2022-2-23' AND `date` <= '2022-2-28' AND `browser` = 'Chrome' AND `browserVers` < '90' GROUP BY `agencyId`, `campname` LIMIT 5000000") 

is.na(Red_100camp) <- Red_100camp == ""
is.na(Red_100camp) <- Red_100camp == "-1"
is.na(Red_100camp) <- Red_100camp == "0"
is.na(Red_100camp) <- Red_100camp == "nf"
is.na(Red_100camp) <- Red_100camp == "tm"

## Cleaning and Format

Red_100camp$`sum(clickOut)` <- as.numeric(Red_100camp$`sum(clickOut)`)
Red_100camp$agencyId <- as.integer(Red_100camp$agencyId)
Red_100camp <- na.omit(Red_100camp) 
setnames(Red_100camp, "sum(clickOut)", "old_chromeCk")


## Query w all Gross Clicks for All Campaigns

gross_100camp <- sqlQuery(ConMy, "SELECT SQL_CALC_FOUND_ROWS SUM(`gross`), `agencyId`, `campname` FROM externalAgenciesReport.comparisonView WHERE `date` >= '2022-2-23' AND `date` <= '2022-2-28' GROUP BY `agencyId`, `campname` LIMIT 800000")


### Joining 1- Adding TotalClicks + Totalgross
## Tipos de Columnas deben ser iguales para hacer el join

Red_brorev100camp <- left_join(Red_100camp, gross_100camp, by = c("campname", "agencyId")) 
setnames(Red_brorev100camp, "SUM(`gross`)", "gross_total")


## Query w all Chrome ClicksOut

allChromeClicks_100camp <- dbGetQuery (conCH, "SELECT SUM(`clickOut`), `agencyId`, `campname` FROM ext_Lastmonth.browserName_browserVersion WHERE `date` >= '2022-2-23' AND `date` <= '2022-2-28' AND `browser` = 'Chrome' GROUP BY `agencyId`, `campname` LIMIT 1000000")



allChromeClicks_100camp$agencyId <- as.integer(allChromeClicks_100camp$agencyId)


### Joining 2 - Adding Total Chrome Clicksout

RedbrorevClicks_100camp <- left_join(Red_brorev100camp, allChromeClicks_100camp, by = c("campname", "agencyId"))
setnames(RedbrorevClicks_100camp, "sum(clickOut)", "Chrome_clicks")

### Query for All Clicks Out 

allClicks_100camp <- dbGetQuery (conCH, "SELECT SUM(`clickOut`), `agencyId`, `campname` FROM ext_Lastmonth.browserName_browserVersion WHERE `date` >= '2022-2-23' AND `date` <= '2022-2-28' GROUP BY `agencyId`, `campname` LIMIT 5000000")

allClicks_100camp$agencyId <- as.integer(allClicks_100camp$agencyId)


#### Joining 3 - Adding Total Clicks 

redbrow_withallClicks_100camp <- left_join(RedbrorevClicks_100camp, allClicks_100camp, by = c("campname", "agencyId")) 
setnames(redbrow_withallClicks_100camp, "sum(clickOut)", "Clicks_total")

#### Query 4

agencies_nam <- sqlQuery(ConMy,"SELECT id, name FROM externalAgencies.agencies LIMIT 1000")
setnames(agencies_nam, "id", "agencyId")

### Joining 4 - Agencies Id + names 

Redflag_100camp <- left_join(redbrow_withallClicks_100camp, agencies_nam, by = "agencyId")
Redflag_100camp <- within(Redflag_100camp, agency <- paste(Redflag_100camp$name, Redflag_100camp$agencyId, sep=' ')) 


### Query 5 Declined Rate

declinedRatebyCampaigns <- sqlQuery(ConMy, "SELECT SQL_CALC_FOUND_ROWS AVG(`declinedRateCOut`), `agencyId`, `campName` FROM externalAgenciesReport.declinedRate WHERE `date` >= '2022-2-23' AND `date` <= '2022-2-28' GROUP BY `agencyId`, `campName` LIMIT 1000000")

setnames(declinedRatebyCampaigns, "campName", "campname")
setnames(declinedRatebyCampaigns, "AVG(`declinedRateCOut`)", "declinadedRate_avg")

declinedRatebyCampaigns$declinadedRate_avg <- round(declinedRatebyCampaigns$declinadedRate_avg, digits=2)


### Joining 5 w Decline Rate 

camp100 <- left_join(Redflag_100camp, declinedRatebyCampaigns, by = c("campname", "agencyId"))


### Adding New Columns with calculations

camp100$cpc <- as.numeric(camp100$gross_total / camp100$Clicks_total)
camp100$cpc <- round(camp100$cpc, digits=2)

camp100$oldclicksrate <- as.numeric(camp100$old_chromeCk / camp100$Clicks_total) 
camp100$oldclicksrate <- round(camp100$oldclicksrate, digits=2)

camp100$gross_oldbrowser <- as.numeric(camp100$old_chromeCk * camp100$cpc)
camp100$agencyId <- as.character(camp100$agencyId)

## To omit NA

 is.na(camp100) <- camp100 == "Inf"
camp100 <- na.omit(camp100)  



### Query Clicks yesterday

clickscamp_yest <- dbGetQuery (conCH, "SELECT SUM(`clickOut`), `campname`, `agencyId` FROM ext_Lastmonth.browserName_browserVersion WHERE `date` = '2022-2-27' GROUP BY `campname`, `agencyId` LIMIT 1000000")

setnames(clickscamp_yest, "sum(clickOut)", "clickscamp_yest")


df_camp100 <- full_join(camp100, clickscamp_yest, by = c("campname", "agencyId"))

## To omit NA

 is.na(df_camp100) <- df_camp100 == "Inf"
df_camp100 <- na.omit(df_camp100)  



### Exporting the Table 
write.table(df_camp100, file= "camp100_feb28.csv", sep = ",", row.names = F)





```
```{r, Graph by Campaigns}

## in % 

library(ggplot2)

camp100_pro <- camp100 %>%
   arrange(desc(old_chromeClicksOut)) 



camp100_pro %>%
  head(20) %>%
ggplot(aes(x=campname, y=oldclicksrate, group=1)) +
  geom_line(color="red", size = 2)+
  geom_point(color = "black", size = 5) + 
    geom_hline(yintercept = mean(camp100$oldclicksrate), size = 1) +
  scale_y_continuous(n.breaks = 10, labels = percent_format()) +
  theme(axis.text.x = element_text(face = "bold", angle = 90, hjust = 1)) +
 labs( title = "Old cicks Rate", 
         subtitle = "by Campaigns from Feb 1 - 8", 
         x = "",
         y = "Old clicks Rate")

mean(camp100_pro$oldclicksrate)

## In Money
camp100_pro %>%
  head(20) %>%
ggplot(aes(x=campname, y=old_chromeRev, group=1))+
  geom_line(color="red", size = 2) +
  geom_point(color = "black", size = 5) + 
  geom_hline(yintercept = 1000, size = 1) +
  scale_y_continuous(n.breaks = 10, labels = dollar_format()) +
 theme(axis.text.x = element_text(face = "bold", angle = 90, hjust = 1)) +
   labs( title = "Estimate revenue from old browsers $", 
         subtitle = "Feb 1 - 8", 
         x = "",
         y = " Estimate gross Revenue")

mean(camp100_pro$old_chromeRev)

```



```{r Orange Flag - Top 100 campaigns}

## Query Campaigns with Old Chrome, order by Clicks Out

orange_100camp <- dbGetQuery (conCH, "SELECT SUM(`clickOut`), `agencyId`, `campname` FROM ext_Lastmonth.browserName_browserVersion WHERE `date` >= '2022-2-23' AND `date` <= '2022-2-28' AND `browser` = 'Chrome' AND `browserVers` >= '90' AND `browserVers` < '95' GROUP BY `agencyId`, `campname` LIMIT 5000000") 

is.na(orange_100camp) <- orange_100camp == ""
is.na(orange_100camp) <- orange_100camp == "-1"
is.na(orange_100camp) <- orange_100camp == "0"
is.na(orange_100camp) <- orange_100camp == "nf"
is.na(orange_100camp) <- orange_100camp == "tm"

## Cleaning and Format

orange_100camp$`sum(clickOut)` <- as.numeric(orange_100camp$`sum(clickOut)`)
orange_100camp$agencyId <- as.integer(orange_100camp$agencyId)
orange_100camp <- na.omit(orange_100camp) 
setnames(orange_100camp, "sum(clickOut)", "old_chromeCk")


## Query w all Gross Clicks for All Campaigns

gross_100camp <- sqlQuery(ConMy, "SELECT SQL_CALC_FOUND_ROWS SUM(`gross`), `agencyId`, `campname` FROM externalAgenciesReport.comparisonView WHERE `date` >= '2022-2-23' AND `date` <= '2022-2-28' GROUP BY `agencyId`, `campname` LIMIT 800000")


### Joining 1- Adding TotalClicks + Totalgross
## Tipos de Columnas deben ser iguales para hacer el join

orange_brorev100camp <- left_join(orange_100camp, gross_100camp, by = c("campname", "agencyId")) 
setnames(orange_brorev100camp, "SUM(`gross`)", "gross_total")


## Query w all Chrome ClicksOut

allChromeClicks_100camp <- dbGetQuery (conCH, "SELECT SUM(`clickOut`), `agencyId`, `campname` FROM ext_Lastmonth.browserName_browserVersion WHERE `date` >= '2022-2-23' AND `date` <= '2022-2-28' AND `browser` = 'Chrome' GROUP BY `agencyId`, `campname` LIMIT 1000000")

allChromeClicks_100camp$agencyId <- as.integer(allChromeClicks_100camp$agencyId)


### Joining 2 - Adding Total Chrome Clicks Out

orangebrorevClicks_100camp <- left_join(orange_brorev100camp, allChromeClicks_100camp, by = c("campname", "agencyId"))
setnames(orangebrorevClicks_100camp, "sum(clickOut)", "Chrome_clicks")

### Query for All Clicks Out 

allClicks_100camp <- dbGetQuery (conCH, "SELECT SUM(`clickOut`), `agencyId`, `campname` FROM ext_Lastmonth.browserName_browserVersion WHERE `date` >= '2022-2-23' AND `date` <= '2022-2-28' GROUP BY `agencyId`, `campname` LIMIT 5000000")

allClicks_100camp$agencyId <- as.integer(allClicks_100camp$agencyId)


#### Joining 3 - Adding Total Clicks 

orangebrow_withallClicks_100camp <- left_join(orangebrorevClicks_100camp, allClicks_100camp, by = c("campname", "agencyId")) 
setnames(orangebrow_withallClicks_100camp, "sum(clickOut)", "Clicks_total")

#### Query 4

agencies_nam <- sqlQuery(ConMy,"SELECT id, name FROM externalAgencies.agencies LIMIT 1000")
setnames(agencies_nam, "id", "agencyId")

### Joining 4 - Agencies Id + names 

orangeflag_100camp <- left_join(orangebrow_withallClicks_100camp, agencies_nam, by = "agencyId")
orangeflag_100camp <- within(orangeflag_100camp, agency <- paste(orangeflag_100camp$name, orangeflag_100camp$agencyId, sep=' ')) 


### Query 5 Declined Rate

declinedRatebyCampaigns <- sqlQuery(ConMy, "SELECT SQL_CALC_FOUND_ROWS AVG(`declinedRateCOut`), `agencyId`, `campName` FROM externalAgenciesReport.declinedRate WHERE `date` >= '2022-2-23' AND `date` <= '2022-2-28' GROUP BY `agencyId`, `campName` LIMIT 1000000")

setnames(declinedRatebyCampaigns, "campName", "campname")
setnames(declinedRatebyCampaigns, "AVG(`declinedRateCOut`)", "declinadedRate_avg")

declinedRatebyCampaigns$declinadedRate_avg <- round(declinedRatebyCampaigns$declinadedRate_avg, digits=2)


### Joining 5 w Decline Rate 

camp100 <- left_join(orangeflag_100camp, declinedRatebyCampaigns, by = c("campname", "agencyId"))


### Adding New Columns with calculations

camp100$cpc <- as.numeric(camp100$gross_total / camp100$Clicks_total)
camp100$cpc <- round(camp100$cpc, digits=2)

camp100$oldclicksrate <- as.numeric(camp100$old_chromeCk / camp100$Clicks_total) 
camp100$oldclicksrate <- round(camp100$oldclicksrate, digits=2)

camp100$gross_oldbrowser <- as.numeric(camp100$old_chromeCk * camp100$cpc)
camp100$agencyId <- as.character(camp100$agencyId)

## To omit NA

 is.na(camp100) <- camp100 == "Inf"
camp100 <- na.omit(camp100)  



### Query Clicks yesterday

clickscamp_yest <- dbGetQuery (conCH, "SELECT SUM(`clickOut`), `campname`, `agencyId` FROM ext_Lastmonth.browserName_browserVersion WHERE `date` = '2022-2-27' GROUP BY `campname`, `agencyId` LIMIT 1000000")

setnames(clickscamp_yest, "sum(clickOut)", "clickscamp_yest")


df_orangecamp100 <- full_join(camp100, clickscamp_yest, by = c("campname", "agencyId"))

## To omit NA

 is.na(df_orangecamp100) <- df_orangecamp100 == "Inf"
df_orangecamp100 <- na.omit(df_orangecamp100)  



### Exporting the Table 
write.table(df_orangecamp100, file= "orange_camp100_feb28.csv", sep = ",", row.names = F)





```
```{r, Graph by Campaigns}

## in % 

library(ggplot2)

camp100_pro <- camp100 %>%
   arrange(desc(old_chromeClicksOut)) 



camp100_pro %>%
  head(20) %>%
ggplot(aes(x=campname, y=oldclicksrate, group=1)) +
  geom_line(color="red", size = 2)+
  geom_point(color = "black", size = 5) + 
    geom_hline(yintercept = mean(camp100$oldclicksrate), size = 1) +
  scale_y_continuous(n.breaks = 10, labels = percent_format()) +
  theme(axis.text.x = element_text(face = "bold", angle = 90, hjust = 1)) +
 labs( title = "Old cicks Rate", 
         subtitle = "by Campaigns from Feb 1 - 8", 
         x = "",
         y = "Old clicks Rate")

mean(camp100_pro$oldclicksrate)

## In Money
camp100_pro %>%
  head(20) %>%
ggplot(aes(x=campname, y=old_chromeRev, group=1))+
  geom_line(color="red", size = 2) +
  geom_point(color = "black", size = 5) + 
  geom_hline(yintercept = 1000, size = 1) +
  scale_y_continuous(n.breaks = 10, labels = dollar_format()) +
 theme(axis.text.x = element_text(face = "bold", angle = 90, hjust = 1)) +
   labs( title = "Estimate revenue from old browsers $", 
         subtitle = "Feb 1 - 8", 
         x = "",
         y = " Estimate gross Revenue")

mean(camp100_pro$old_chromeRev)

```



```{r}
knitr::knit_exit()
```
## By Campaigns 
### Replace the Agency Id and Date in the 5 queries (also Declined Rate Query)
```{r Red Flag, for Campaigns above the avg. line}

### Agency 86

query1 <- sqlQuery (ConMy, "SELECT SQL_CALC_FOUND_ROWS SUM(`gross`), SUM(`clicksOut`), `agencyId`, `campname` FROM externalAgenciesReport.comparisonView WHERE `date` >= '2022-2-23' AND `date` <= '2022-2-28' AND `agencyId` = '86' GROUP BY `agencyId`, `campname` ORDER BY SUM(`gross`) DESC LIMIT 100000")
setnames(query1, "SUM(`gross`)", "TotalGrossReve")
setnames(query1, "SUM(`clicksOut`)", "Invalid_TotalClicksOut")

query2 <- dbGetQuery (conCH, "SELECT SUM(`clickOut`), `agencyId`, `campname` FROM ext_Lastmonth.browserName_browserVersion WHERE `date` >= '2022-2-23' AND `date` <= '2022-2-28' AND `browser` = 'Chrome' AND `agencyId` = '86' GROUP BY `agencyId`, `campname` ORDER BY SUM(`clickOut`) DESC LIMIT 100000") 
setnames(query2, "sum(clickOut)", "TotalChromeClicksOut")


query3 <- dbGetQuery (conCH, "SELECT SUM(`clickOut`), `agencyId`, `campname` FROM ext_Lastmonth.browserName_browserVersion WHERE `date` >= '2022-2-23' AND `date` <= '2022-2-28' AND `browser` = 'Chrome' AND `browserVers` < '90' AND `agencyId` = '86' GROUP BY `agencyId`, `campname` ORDER BY SUM(`clickOut`) DESC LIMIT 100000") 
setnames(query3, "sum(clickOut)", "old_chromeClicksOut")
query3$old_chromeClicksOut <- as.numeric(query3$old_chromeClicksOut)

query4 <- dbGetQuery (conCH, "SELECT SUM(`clickOut`), `agencyId`, `campname` FROM ext_Lastmonth.browserName_browserVersion WHERE `date` >= '2022-2-23' AND `date` <= '2022-2-28' AND `agencyId` = '86' GROUP BY `agencyId`, `campname` ORDER BY SUM(`clickOut`) DESC LIMIT 100000") 
setnames(query4, "sum(clickOut)", "TotalClicksOut")


## Query 5::Declined Rate

declinedRatebyCampaigns <- sqlQuery(ConMy, "SELECT SQL_CALC_FOUND_ROWS AVG(`declinedRateCOut`), `agencyId`, `campName` FROM externalAgenciesReport.declinedRate WHERE `date` >= '2022-2-23' AND `date` <= '2022-2-28' GROUP BY `agencyId`, `campName` LIMIT 1000000")

setnames(declinedRatebyCampaigns, "campName", "campname")
setnames(declinedRatebyCampaigns, "AVG(`declinedRateCOut`)", "avg_declinadedRate")



### Joining Tables 

q1_2 <- inner_join(query1, query2, by = "campname")
camp_agency <- inner_join(q1_2, query3, by = "campname") 

query4_allclicks <- inner_join(camp_agency, query4, by = "campname")


### Joining Adding Decline Rate 

campaigns <- left_join(query4_allclicks, declinedRatebyCampaigns, by = "campname")



## Adding Calculations: old Chrome Rate, Old Chrome Revenue


campaigns$rate_redFlag <- as.numeric(campaigns$old_chromeClicksOut / campaigns$TotalClicksOut) 
campaigns$rate_redFlag <- round(campaigns$rate_redFlag, digits=2)

campaigns$cpc <- as.numeric(campaigns$TotalGrossReve / campaigns$TotalClicksOut)
campaigns$cpc <- round(campaigns$cpc, digits=2)

campaigns$reve_redFlag <- as.numeric(campaigns$old_chromeClicksOut * campaigns$cpc)






## Exporting Full Table 


write.table(campaigns, file= "campaign.csv", sep = ",", row.names = F)





```



